# Use root/example as user/password credentials
version: "3"

services:

  db:
    image: mysql:latest
    container_name: mysql-db-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306