version: '3.6'

services:

  db:
    image: ravendb/ravendb
    restart: always
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      - RAVEN_ARGS='--Setup.Mode=None'
      - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'
