version: "3"

services:

  db:
    container_name: mssql-db-server
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
      - "1433:1433"
    # IT DOESN'T WORK... 
    # https://github.com/Microsoft/mssql-docker/issues/136#issuecomment-531590985
    volumes:
      - ./data:/var/opt/mssql
    environment:
      # The password must be at least 8 characters.. -> change_this_password
      # https://github.com/Microsoft/mssql-docker/issues/283
      SA_PASSWORD: "Your_password123" 
      ACCEPT_EULA: "Y"

  adminer:
    image: "adminer:latest"
    restart: always
    ports:
      - "8090:8080"
    depends_on:
      - db
